wallpaper {
    monitor = DP-1
    path = ~/wallpapers/1920x1080/0001.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/wallpapers/1920x1080/0002.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/wallpapers/1920x1080/0003.jpg
    fit_mode = cover
}
